version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    container_name: social-media-db
    volumes:
      - social_media_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socialDB
      - DATABASE_HOST=54321
    ports:
      - "54321:5432"
    restart: always
    networks:
      - social-media-network

  app:
    container_name: social-media-api
    build:
      context: .
      dockerfile: Dockerfile
    #env_file:
    #  - .env
    environment:
      - APP_ENV=local
      - JWT_AT_PRIVATE_KEY=JWT_SECRET
      - JWT_AT_EXPIRATION_MIN=300
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=socialDB
      - DB_HOST=social-media-db
      - DB_PORT=5432
      - SERVER_PORT=3000
      - DATABASE_URL= postgres://postgres:postgres@postgresdb:54321/socialDB?sslmode=disable
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgresdb
    networks:
      - social-media-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    restart: always
    networks:
      - social-media-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - social-media-network


networks:
  social-media-network:
    driver: bridge


volumes:
  api:
  social_media_postgres_data: