version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    container_name: social-media-db
    volumes:
      - database_postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - social-media-network

  app:
    container_name: social-media-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgresdb
    networks:
      - social-media-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    restart: always
    networks:
      - social-media-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - social-media-network


networks:
  social-media-network:
    driver: bridge


volumes:
  api:
  database_postgres: